#### Generate Hilbert matrix with list comprehension

In [4]:
%precision 5
def hilbertmatrix(a):
    return [[1/(i+j+1) for j in range(a)] for i in range(a)]

In [5]:
print(hilbertmatrix(7))

[[1.0, 0.5, 0.3333333333333333, 0.25, 0.2, 0.16666666666666666, 0.14285714285714285], [0.5, 0.3333333333333333, 0.25, 0.2, 0.16666666666666666, 0.14285714285714285, 0.125], [0.3333333333333333, 0.25, 0.2, 0.16666666666666666, 0.14285714285714285, 0.125, 0.1111111111111111], [0.25, 0.2, 0.16666666666666666, 0.14285714285714285, 0.125, 0.1111111111111111, 0.1], [0.2, 0.16666666666666666, 0.14285714285714285, 0.125, 0.1111111111111111, 0.1, 0.09090909090909091], [0.16666666666666666, 0.14285714285714285, 0.125, 0.1111111111111111, 0.1, 0.09090909090909091, 0.08333333333333333], [0.14285714285714285, 0.125, 0.1111111111111111, 0.1, 0.09090909090909091, 0.08333333333333333, 0.07692307692307693]]


#### Check Hilbert matrix with function methods

In [3]:
#check with scipy.linalg
from scipy import linalg
from scipy.linalg import hilbert
%precision 3

print('Hilbert Matrix using scipy.linalg.hilbert:')
print(hilbert(7))
print()
print('Difference between two matrices:')
print(hilbert(7)-hilbertmatrix(7))

Hilbert Matrix using scipy.linalg.hilbert:
[[1.    0.5   0.333 0.25  0.2   0.167 0.143]
 [0.5   0.333 0.25  0.2   0.167 0.143 0.125]
 [0.333 0.25  0.2   0.167 0.143 0.125 0.111]
 [0.25  0.2   0.167 0.143 0.125 0.111 0.1  ]
 [0.2   0.167 0.143 0.125 0.111 0.1   0.091]
 [0.167 0.143 0.125 0.111 0.1   0.091 0.083]
 [0.143 0.125 0.111 0.1   0.091 0.083 0.077]]

Difference between two matrices:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [4]:
import numpy as np

#### Print unit vector using list comprehension

In [5]:
unit_vector=[[1 if i==j else 0 for i in range(7)] for j in range(7)]

In [6]:
unit=(np.array(unit_vector).T)

In [7]:
print(unit)

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


#### Solving for inverse using unit vectors

In [8]:
inv7_=[np.linalg.solve(hilbertmatrix(7),unit[i])for i in range(7)]

In [9]:
inv7_unit=(np.array(inv7_).T)
print(inv7_unit)

[[ 4.900e+01 -1.176e+03  8.820e+03 -2.940e+04  4.851e+04 -3.881e+04
   1.201e+04]
 [-1.176e+03  3.763e+04 -3.175e+05  1.129e+06 -1.940e+06  1.597e+06
  -5.045e+05]
 [ 8.820e+03 -3.175e+05  2.858e+06 -1.058e+07  1.871e+07 -1.572e+07
   5.045e+06]
 [-2.940e+04  1.129e+06 -1.058e+07  4.032e+07 -7.277e+07  6.209e+07
  -2.018e+07]
 [ 4.851e+04 -1.940e+06  1.871e+07 -7.277e+07  1.334e+08 -1.153e+08
   3.784e+07]
 [-3.881e+04  1.597e+06 -1.572e+07  6.209e+07 -1.153e+08  1.006e+08
  -3.330e+07]
 [ 1.201e+04 -5.045e+05  5.045e+06 -2.018e+07  3.784e+07 -3.330e+07
   1.110e+07]]


#### check inverse vectors with H7^(-1)

In [10]:
H7inv_=np.linalg.inv(hilbertmatrix(7))

In [11]:
print('Inverse using np.linalg.inv:')
print(H7inv_)
print()
print('Difference between two matrices:')
print(H7inv_-inv7_unit)

Inverse using np.linalg.inv:
[[ 4.900e+01 -1.176e+03  8.820e+03 -2.940e+04  4.851e+04 -3.881e+04
   1.201e+04]
 [-1.176e+03  3.763e+04 -3.175e+05  1.129e+06 -1.940e+06  1.597e+06
  -5.045e+05]
 [ 8.820e+03 -3.175e+05  2.858e+06 -1.058e+07  1.871e+07 -1.572e+07
   5.045e+06]
 [-2.940e+04  1.129e+06 -1.058e+07  4.032e+07 -7.277e+07  6.209e+07
  -2.018e+07]
 [ 4.851e+04 -1.940e+06  1.871e+07 -7.277e+07  1.334e+08 -1.153e+08
   3.784e+07]
 [-3.881e+04  1.597e+06 -1.572e+07  6.209e+07 -1.153e+08  1.006e+08
  -3.330e+07]
 [ 1.201e+04 -5.045e+05  5.045e+06 -2.018e+07  3.784e+07 -3.330e+07
   1.110e+07]]

Difference between two matrices:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### Check inverse vectors with hilbert 7^(-1)

In [12]:
H7inv=np.linalg.inv(hilbert(7))

In [13]:
print('Inverse using np.linalg.invhilbert:')
print(H7inv)
print()
print('Difference between two matrices:')
print(H7inv-inv7_unit)

Inverse using np.linalg.invhilbert:
[[ 4.900e+01 -1.176e+03  8.820e+03 -2.940e+04  4.851e+04 -3.881e+04
   1.201e+04]
 [-1.176e+03  3.763e+04 -3.175e+05  1.129e+06 -1.940e+06  1.597e+06
  -5.045e+05]
 [ 8.820e+03 -3.175e+05  2.858e+06 -1.058e+07  1.871e+07 -1.572e+07
   5.045e+06]
 [-2.940e+04  1.129e+06 -1.058e+07  4.032e+07 -7.277e+07  6.209e+07
  -2.018e+07]
 [ 4.851e+04 -1.940e+06  1.871e+07 -7.277e+07  1.334e+08 -1.153e+08
   3.784e+07]
 [-3.881e+04  1.597e+06 -1.572e+07  6.209e+07 -1.153e+08  1.006e+08
  -3.330e+07]
 [ 1.201e+04 -5.045e+05  5.045e+06 -2.018e+07  3.784e+07 -3.330e+07
   1.110e+07]]

Difference between two matrices:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### Multiply H7 and H7^(-1)

In [14]:
print('H7@inv(H7):')
print(hilbert(7)@H7inv)

H7@inv(H7):
[[ 1.000e+00  1.232e-11  9.884e-12  1.600e-10  2.321e-10 -1.333e-09
   1.177e-11]
 [-2.274e-13  1.000e+00 -1.164e-10  0.000e+00 -9.313e-10 -9.313e-10
   0.000e+00]
 [-2.257e-13  6.345e-12  1.000e+00  2.279e-10  5.945e-10 -1.450e-09
  -1.672e-11]
 [ 2.031e-13 -8.621e-12  9.785e-11  1.000e+00  1.607e-09 -1.023e-09
   6.161e-11]
 [-2.591e-13  1.923e-11  2.147e-12 -1.568e-10  1.000e+00  2.123e-10
  -4.588e-10]
 [ 8.539e-13 -1.707e-11  1.901e-10 -2.947e-10  1.843e-09  1.000e+00
   1.039e-10]
 [ 7.958e-13 -2.183e-11 -2.910e-10  2.328e-10  9.313e-10  1.397e-09
   1.000e+00]]


#### Substract the product from identity matrix e7

In [15]:
#use np.dientiy generate unit matrix
e7=np.identity(7)
print('H7@inv(H7)-e(7):')
print((hilbert(7)@H7inv)-e7)

H7@inv(H7)-e(7):
[[-1.927e-13  1.232e-11  9.884e-12  1.600e-10  2.321e-10 -1.333e-09
   1.177e-11]
 [-2.274e-13  2.183e-11 -1.164e-10  0.000e+00 -9.313e-10 -9.313e-10
   0.000e+00]
 [-2.257e-13  6.345e-12  1.758e-10  2.279e-10  5.945e-10 -1.450e-09
  -1.672e-11]
 [ 2.031e-13 -8.621e-12  9.785e-11 -6.242e-10  1.607e-09 -1.023e-09
   6.161e-11]
 [-2.591e-13  1.923e-11  2.147e-12 -1.568e-10  3.918e-10  2.123e-10
  -4.588e-10]
 [ 8.539e-13 -1.707e-11  1.901e-10 -2.947e-10  1.843e-09 -2.019e-09
   1.039e-10]
 [ 7.958e-13 -2.183e-11 -2.910e-10  2.328e-10  9.313e-10  1.397e-09
   2.328e-10]]


#### Invert and print H7^(-1)

In [16]:
H7inv=np.linalg.inv(hilbert(7))
print('inv(invH7):')
print(np.linalg.inv(H7inv))
print()
print('compare with hilbert(7):')
print(hilbert(7))

inv(invH7):
[[1.    0.5   0.333 0.25  0.2   0.167 0.143]
 [0.5   0.333 0.25  0.2   0.167 0.143 0.125]
 [0.333 0.25  0.2   0.167 0.143 0.125 0.111]
 [0.25  0.2   0.167 0.143 0.125 0.111 0.1  ]
 [0.2   0.167 0.143 0.125 0.111 0.1   0.091]
 [0.167 0.143 0.125 0.111 0.1   0.091 0.083]
 [0.143 0.125 0.111 0.1   0.091 0.083 0.077]]

compare with hilbert(7):
[[1.    0.5   0.333 0.25  0.2   0.167 0.143]
 [0.5   0.333 0.25  0.2   0.167 0.143 0.125]
 [0.333 0.25  0.2   0.167 0.143 0.125 0.111]
 [0.25  0.2   0.167 0.143 0.125 0.111 0.1  ]
 [0.2   0.167 0.143 0.125 0.111 0.1   0.091]
 [0.167 0.143 0.125 0.111 0.1   0.091 0.083]
 [0.143 0.125 0.111 0.1   0.091 0.083 0.077]]


#### Substract from H7

In [17]:
print('inv(invH7)-hilbert(7):')
print(np.linalg.inv(H7inv)-hilbert(7))

inv(invH7)-hilbert(7):
[[1.837e-10 1.612e-10 1.431e-10 1.285e-10 1.166e-10 1.066e-10 9.827e-11]
 [5.144e-11 4.987e-11 4.710e-11 4.410e-11 4.123e-11 3.857e-11 3.618e-11]
 [2.613e-11 2.826e-11 2.825e-11 2.740e-11 2.623e-11 2.497e-11 2.372e-11]
 [1.485e-11 1.829e-11 1.936e-11 1.938e-11 1.894e-11 1.829e-11 1.756e-11]
 [8.046e-12 1.209e-11 1.371e-11 1.423e-11 1.420e-11 1.392e-11 1.350e-11]
 [3.498e-12 7.833e-12 9.771e-12 1.058e-11 1.083e-11 1.078e-11 1.058e-11]
 [3.237e-13 4.780e-12 6.902e-12 7.904e-12 8.330e-12 8.446e-12 8.389e-12]]
